#!/bin/bash

kubectl create ns api-demo 2>/dev/null
kubectl config set-context --current --namespace=api-demo 2>/dev/null

kubectl create -f car-dealership.yaml
waitsvc car 
url=$(kubectl get svc | grep Load | awk '{print $4}')
echo "Waiting for LoadBalancer to be available"
sleep 90
echo "Use browser to test api endpoints (car,dealer)  at http://$url"

read -p "Do you want to populate the car dealership api demo(y/n)? " -n 1 -r
echo
if [[ $REPLY =~ [Yy]$ ]]; then 
  echo "Populating api-demo car-dealership"
  cd populate 
  populate
  cd ..
fi


