#!/bin/bash
# Updates all compliance rules in a single shot. 
# Updating all rules at the same time makes it possible 
# to maintain strict ordering between rules.

if [ "$#" -ne 1 ]; then
    echo "You must pass in CI image policy json file"
else
   curl -k -u $TL_USER:$TL_USER_PW -X PUT -H "Content-Type:application/json" \
        $TL_CONSOLE_API/policies/compliance/ci/images --data-binary "@$1"
fi

