# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/app
    #docker:
      # specify the version
      # - image: circleci/golang:1.8
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    # working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # specify any bash command here prefixed with run: 
      - run: echo "Hello World"
      #- image: circleci/classic:latest
      - run: curl https://location.of.twistcli.binary/twistcli
      - run: sudo chmod a+x ./twistcli
      - run: docker pull ubuntu:latest
      - run: sudo ./twistcli--tlsverify=false -c https://CONSOLE.IP.HERE:8083 -u admin -p PASSWORDHERE -i ubuntu:latest