#!/bin/bash
# Updates all compliance rules in a single shot. 
# Updating all rules at the same time makes it possible 
# to maintain strict ordering between rules.

base='deployedComplianceRules'
file="$base.json"
endpoint='policies/compliance/container'

putDataREST $endpoint $file

