#!/bin/bash
# must pass in acceskey json file 

curl -v --request POST \
  --url $PC_API_URL/v2/user \
  --header 'Content-Type: application/json' \
  --header "x-redlock-auth: $PC_API_TOKEN" \
  --data @user.json



# curl -s  \
#  --url $PC_API_URL/login \
#  --header 'accept: application/json; charset=UTF-8' \
#  --header 'content-type: application/json; charset=UTF-8' \
#  --data @$1 | jq .token | sed 's/\"//g' 


 


