#!/bin/bash
# Updates all compliance rules in a single shot. 
# Updating all rules at the same time makes it possible 
# to maintain strict ordering between rules.

if [ "$#" -ne 1 ]; then
    echo "You must pass in vulnerability policy json file"
else
   curl -k -u admin:$TL_ADMIN_PW -X PUT -H "Content-Type:application/json" \
        $TL_CONSOLE_HTTPS/api/v1/policies/compliance --data-binary "@$1"
fi

