#!/bin/bash

[ -z "$TL_RELEASE" ] && echo "You must setup environment first and define TL_RELEASE" && exit -1

[ ! -d "$TL_INSTALL_ROOT_FOLDER" ] && echo "You must create '$TL_INSTALL_ROOT_FOLDER'  manually before installation" && exit -2 

installFolder=$TL_INSTALL_ROOT_FOLDER/$TL_RELEASE
mkdir -p $installFolder 
pushd $installFolder > /dev/null

echo "Downloading Prisma Cloud Compute release in folder $installFolder"
wget -q $TL_RELEASE_URL
tar xzf prisma*.tar.gz
cat version.txt 

rm prisma_cloud_compute_edition*.tar.gz

popd > /dev/null

echo "Download complete"


