#!/bin/bash
  
[ -z "$TL_RELEASE" ] && echo "You must setup environment first and define TL_RELEASE" && exit -1

installFolder=$TL_INSTALL_ROOT_FOLDER/$TL_RELEASE

if [ ! -d "$installFolder" ]; then
   echo "You must first run 'downloadSoftware'"
else
  cd $installFolder
  sudo ./twistlock.sh -ys console
  cd ..
fi


