#!/bin/bash

(( $# < 1 )) && \
  echo "Pass in a IaC file to scan and optionally twistcli scan options." && \
  echo "Run 'scanIaC --help' to see available scan options." && exit -1

[[ "$1" == "--help" ]] && twistcli IaCs scan --help && exit 1

params=""
verbose=false
IaC=""

# params to twistcli includes IaC to scan as last one
if [ "$1" == '-v' ]; then
  IaC="$2"
  params="${@:3}"
  verbose=true
else
  IaC=$1
  params="$@:2"
fi

SCAN="twistcli"
[[ "$CRIO" == "true" ]] && IaC="localhost/$IaC" && \
   SCAN="sudo $TL_DEMO_ROOT_FOLDER/scripts/twistcli"
   
# pass in v to get verbose print_msgs
print_msg() {
   [ "$verbose" == "true" ] && echo $1 
} 

print_msg "This only works with 20.04 hosted release and uses --ci flag"
print_msg "scan results saved on $TL_CONSOLE/#!/monitor/vulnerabilities/IaCs/ci"

echo
echo "--------- Utilizing twistcli to perform IaC scan of $IaC ---------------"
result=$($SCAN iac scan -u $TL_USER -p $TL_USER_PW --address $TL_CONSOLE \
   $IaC $params | grep -v DATA)

printf "%s\n" "$result"

result=$(echo $result | grep -c "Scan failed due to")

echo "----------------- twistcli scan of $IaC complete -----------------------"
exit $result

