#!/bin/bash

# use imageId only if 2 or more scan reports have same exact name
# imageId=$(docker image inspect $1 |grep Id | awk -F '"' '{print $4}')

echo $imageId

if [ "$#" -gt 0 ]; then
   echo "retrieving twistcli or Jenkins image scan report for image $1 with ID of $imageId"
   curl -v -sku $TL_USER:$TL_USER_PW -H 'Content-Type: application/json' -o $1_images.json \
        "$TL_CONSOLE_API/scans?search=$1"
else
  echo "retrieving all manual (twistcli or Jenkins) scan reports"
  curl -sku $TL_USER:$TL_USER_PW -o images.json "$TL_CONSOLE_API/scans"
fi

