#!/bin/bash

if [ "$#" -gt 0 ]; then
   echo "retrieving image scan reports for images with $1 in name"
   curl -sku $TL_USER:$TL_USER_PW -o $1_images.json "$TL_CONSOLE_API/images?collection=All?search=$1"
else
  echo "retrieving all image scan reports"
  curl -sku $TL_USER:$TL_USER_PW -o images.json "$TL_CONSOLE_API/images?collection=All"
fi


