#!/bin/bash

token=$(curl -sku admin:$TL_ADMIN_PW -H 'Content-Type: application/json' POST -d '{"username": "admin", "password": "'"$TL_ADMIN_PW"'"}' $TL_CONSOLE_HTTPS/api/v1/authenticate) 


status=$?
if [ $status -eq 0 ]
then
  echo $token | sed "s/\"//g" | sed "s/}//g" | cut -d ":" -f2
else
  echo "Error: rerun curl command with -v flag instead of -s to see error"
fi


