#!/bin/bash
echo "This script requires utility jq"

if [ "$#" -ne 1 ]; then
   echo "You must pass in an image name to set model to ACTIVE"
   exit 
fi

rtprofile=$(curl -sku admin:$TL_ADMIN_PW $TL_CONSOLE_HTTPS/api/v1/profiles/container?search=$1 | jq . | grep '_id' | awk -F '"' '{print $4}')

if [ -z "$rtprofile" ]; then
  echo "Could not find image {$1} or some other error occurred!"
  exit
fi

curl -sku admin:$TL_ADMIN_PW -H 'Content-Type: application/json' \
  POST -d '{"state":"manualActive"}' \
  $TL_CONSOLE_HTTPS/api/v1/profiles/container/$rtprofile/learn

status=$?
if [ $status -eq 0 ]
then
  echo "Model for image $1 set to Active"
else
  echo "Error: rerun curl command with -v flag instead of -s to see error"
fi


