#!/bin/bash
#!/bin/bash

openshift="false"
[ "$#" -lt 1 ] && echo "You must enter '1.0' or '2.0'" && exit 1
[ "$#" -eq 2 ] && openshift="true"

echo; echo "Deploying version $1 of Note Maker application"
echo "This is an ephemeral deployment for demo purposes only"
if [ "$openshift" == "true" ]; then
  echo "Deploying into an OpenShift4 environmment"
  alias kubectl=oc
else
  kubectl create ns notemaker
fi

cd $1
kubectl apply -f mongodb.yaml
sleep 10
kubectl apply -f performance-meter.yaml
sleep 10
kubectl apply -f web-service.yaml
sleep 5

if [ "$openshift" == "true" ]; then
   kubectl apply -f oc-nginx.yaml
else
   kubectl apply -f nginx.yaml
   ../scripts/waitsvc nginx
   ip=$(kubectl get svc -n notemaker | grep nginx | awk '{print $4}')
   echo "Use browser to create some notes at http://$ip to generate runtime models"
fi

cd ..

