#!/bin/bash
[ "$#" -lt 1 ] && echo "You must enter '1.0' or '2.0'" && exit 1

echo; echo "Initial deploy of version $1 of Note Maker application"

echo "Creating namespace and storage"
kubectl create ns notemaker 
kubectl create -f data/mongodb-pvc.yaml

sleep 10

deploy $1





