#!/bin/bash
[ "$#" -lt 1 ] && echo "You must enter '1.0' or '2.0'" && exit 1

alias kubectl=oc

echo; echo "Initial deploy of version $1 of Note Maker application into an OpenShift cluster"

echo "Creating namespace(project), giving needed privs, and creating pvc storage"
oc create ns notemaker
oc adm policy add-scc-to-user anyuid system:serviceaccount:notemaker:default
 
oc create -f data/mongodb-pvc.yaml
oc create -f data/web-service-pvc.yaml

sleep 10

oc-deploy $1





