#!/bin/bash

[ "$#" -lt 1 ] && echo "You must enter '1.0' or '2.0' and optionally mongo|web|perf" && exit 1

[ "$#" -eq 1 ] && op=mongowebperf 
[ "$#" -eq 2 ] && op=$2

oc project notemaker > /dev/null

echo; echo "Redeploying version $1 of Note Maker application"
echo "Leveraging existing storage"

cd $1
[[ "$op" == *"mongo"* ]] && kubectl delete -f mongodb.yaml
[[ "$op" == *"web"* ]] && \
  kubectl delete -f oc-web-service.yaml && \
  oc delete route web-service
[[ "$op" == *"perf"* ]] && kubectl delete -f performance-meter.yaml
sleep 10
cd ..

oc-deploy $@



