#!/bin/bash

if [ "$#" -gt 0 ]; then
   echo "retrieving image scan reports for images with $1 in name"
   curl -vk -o $1_images.json "$TL_CONSOLE_HTTP/api/v1/images?search=$1"
else
  echo "retrieving all image scan reports"
  curl -vk -o images.json "$TL_CONSOLE_HTTPS/api/v1/images"
fi


