#!/bin/bash

# You can change base or file (and endpoint if endpoint changes)
base='containerFWRules'
file="$base.json"
endpoint='policies/firewall/app/container'

# leave this alone
../getDataREST $endpoint $base 

