#!/bin/bash

# You can change base or file (and endpoint if endpoint changes)
base='networkFWRules'
file="$base.json"
endpoint='policies/firewall/network/container'

# leave this alone
getDataREST $endpoint $base 


