apiVersion: v1
kind: Service
metadata:
  name: web-service 
  namespace: notemaker
spec:
  selector:
    app: web-service
    tier: web 
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service 
  namespace: notemaker
  labels:
    app: web-service 
    tier: web 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-service 
      tier: web 
  template:
    metadata:
      labels:
        app: web-service 
        tier: web 
    spec:
      containers:
        - name: web-service 
          image: notemaker/websvc:2.0
          imagePullPolicy: Always
          securityContext:
             allowPrivilegeEscalation: false          
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/dev 

